/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pong;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Timer;

public class FrmPong extends javax.swing.JFrame implements KeyListener {

    int pelotaX = 290 , pelotaY = 200;
    int signo=1;
    int signo2=1;
    int paletai=150; //150
    int medidax,mediday,mediday2,medidax1,mediday1;
    int paletad=150; //150
    int velocidad=12;
    
 
    //Deben estar estos 3 metodos siempre presentes
    public void keyTyped(KeyEvent e) {} //tecla de función son las f
    public void keyReleased(KeyEvent e) {} //Cuando soltamos la tecla
    public void keyPressed(KeyEvent e) //Presionamos la tecla
    {
       if (e.getKeyCode()==87)
       {
           paletai-=velocidad;
       }
       else if (e.getKeyCode()==83)
       {
           paletai+=velocidad;
       }
       
       if (e.getKeyCode()==38)
       {
           paletad-=velocidad;
       }
       else if (e.getKeyCode()==40)
       {
           paletad += velocidad;
       }
       System.out.println(e.getKeyCode());
       
    }

    
    public FrmPong() {
        initComponents();
        addKeyListener(this);
    }
        
    public void paint (Graphics g)
    {
        super.paint(g);
        g.setColor(Color.black);
        //g.fillOval(290, 190, 20, 20);
        g.drawOval(pelotaX, pelotaY, 20, 20);
        repaint();
        g.drawRect(0, paletai, 20, 60);
        g.drawRect(580,paletad,20,60);
    }
    
    Timer temporizador = new Timer (10, new ActionListener ()
    {
        
            public void actionPerformed(ActionEvent e)
            {
                
                pelotaX+=signo*2;
                pelotaY+=signo2*2;
                
                if(paletai <= 20)
                {
                    paletai=20;
                }
                else if (paletai >= 340)
                {
                    paletai=340;
                }
                
                //Paletas no superan los limites
                
                if(paletad <= 20)
                {
                    paletad = 20;
                }
                else if (paletad >= 340)
                {
                    paletad = 340;
                }

                if (pelotaY <=22 || pelotaY >=380)
                {
                    signo2*=-1;
//                    
                }
                
                //Golpe con las pelotas
                //paletai y d = 150
                
                mediday=paletai+70;
                mediday1=paletai-2;
                if (pelotaX == 20 && pelotaY >= (paletai-10) && pelotaY <= mediday)
                {
                    signo*=-1;
                }
                
                
                mediday2=paletad+70;
                medidax1=paletad-2; //la misma que medida mediday1
                if (pelotaX == 560 && pelotaY >= (paletad-10) && pelotaY <= mediday2)
                {
                    signo*=-1;
                }
                
                //Cuando la pelota sale de la pantalla
                
                if (pelotaX == 600 || pelotaX == -20)
                {
                    pelotaX=290;
                    pelotaY=200;
                    signo*=-1;
                    signo2*=1;
                }
                
                
                    
                    
                    
                    
//                mediday=paletad+60;
//                medidax=20;
//                
//                if (pelotaY >= paletad || pelotaY <= mediday)
//                {
//                       
//                    if (pelotaY >= paletad || pelotaY <= mediday)
//                    {
//                        signo*=1;
//                        signo2*=1;
//                    }
//                }
//                if (pelotaX < 21)
//                {
//                    signo*=-1;
//                    if (pelotaY >= paletad || pelotaY <= medidax)
//                    {
//                        signo2*=1;
//                    }
//                }
                
                
                
            }
    });
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        temporizador.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
